apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  labels:
    app: python-api-deployment
    app.kubernetes.io/name: python-api-deployment
    app.kubernetes.io/version: v1.0
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-api
      app.kubernetes.io/name: python-api
  template:
    metadata:
      labels:
        app: python-api
        app.kubernetes.io/name: python-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: python-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
          name: flask
          protocol: TCP