# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
imagePullSecrets: []
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  
  hosts:
    - host: python-api.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: python-api-tls
      hosts:
        - python-api.local

resources: {}
